version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
    # reviewers: ["your-github-handle"]  # Optional: add if you want automatic reviewers
    # assignees: ["your-github-handle"]  # Optional: add if you want automatic assignees
    pull-request-branch-name:
      separator: "-"

  # Example additional ecosystem (uncomment as needed)
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "dependencies"
