services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: unless-stopped
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
    command:
      - --provider=google
      - --email-domain=*
      - --upstream=http://api:8000
      - --http-address=0.0.0.0:4180
      - --redirect-url=https://localhost:8444/oauth2/callback
      - --set-xauthrequest=true
    networks:
      - net
networks:
  net:
    driver: bridge
