services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/gateway/certs:/etc/letsencrypt
      - ./docker/certbot/conf:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - net
networks:
  net:
    driver: bridge
