version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "5125:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway:/usr/share/nginx/html:ro
    restart: always
