{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "ultimate-summary.name" . }}
stringData:
{{- range $k, $v in .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
