name: governance-stats-badge

on:
    schedule:
        - cron: "15 2 * * *"
    workflow_dispatch:

jobs:
    update-badge:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install -r governance_app/requirements.txt

            - name: Generate badge
              run: |
                  python scripts/generate_governance_stats_badge.py

            - name: Commit badge and snapshots (if changed)
              run: |
                  git add badge-governance-stats.json metrics-history/*.json 2>/dev/null || true
                  if git diff --cached --quiet; then
                    echo 'No changes to badge or history';
                  else
                    git config user.name 'github-actions'
                    git config user.email 'actions@users.noreply.github.com'
                    git commit -m 'chore(stats): update governance stats badge & history'
                    git push
                  fi

            - name: Badge preview
              run: cat badge-governance-stats.json
