name: tests-and-coverage

on:
    pull_request:
    push:
        branches: [main, master]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  pip install --upgrade pip
                  if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
                  if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
            - name: Run pytest (fast pass) or fallback to smoke
              run: |
                  pytest -q || pytest -q -k smoke
            - name: Coverage (backend)
              run: |
                  # Ratchet: raise bar from 74 -> 79 (current local ~81%)
                  pytest --maxfail=1 --disable-warnings --cov=backend --cov-report=term-missing --cov-fail-under=79
            - name: Upload coverage artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: coverage_html_report
                  if-no-files-found: ignore
