name: trivy-scan

on:
  pull_request:
    paths:
      - 'docker/platforms/Dockerfile.platform'
      - '.github/workflows/trivy-scan.yml'
      - 'requirements_platforms.txt'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      IMAGE_NAME: platform-services
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build image (no push)
        run: |
          docker build -f docker/platforms/Dockerfile.platform -t $IMAGE_NAME:pr-${{ github.event.pull_request.number || github.run_number }} .

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'image'
          image-ref: ${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number || github.run_number }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
