name: Workflow Lint

on:
        pull_request:
                paths:
                        - .github/workflows/**
        push:
                branches: [main, master]
                paths:
                        - .github/workflows/**

jobs:
        invoke:
                # Fully qualified reusable workflow reference; replace OWNER/REPO with your org/user and repository name.
                # Example: uses: your-org/fullstack-ecosystem/.github/workflows/reusable-actionlint.yml@main
                uses: romel/fullstack-ecosystem/.github/workflows/reusable-actionlint.yml@main
                with:
                        actionlint-version: v1.7.0
                        os-matrix: '["ubuntu-latest","macos-latest","windows-latest"]'

        fallback-lint:
                # Executes only if the reusable workflow invocation failed (e.g., wrong reference or transient issue)
                if: failure()
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v4
                        - name: Download actionlint
                          run: |
                                  set -e
                                  VER=v1.7.0
                                  VER_STR=${VER#v}
                                  curl -sSL https://github.com/rhysd/actionlint/releases/download/${VER}/actionlint_${VER_STR}_Linux_x86_64.tar.gz -o actionlint.tgz
                                  tar -xzf actionlint.tgz actionlint
                        - name: Run actionlint
                          run: |
                                  ./actionlint || true
                        - name: Fallback summary
                          run: |
                                  echo "### Fallback Actionlint Run" >> $GITHUB_STEP_SUMMARY
                                  echo "Reusable workflow failed; executed minimal inline lint." >> $GITHUB_STEP_SUMMARY
